title: Using RefWorks for Citation Management
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-shell\">View workshop content in GitHub</a>"
